version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build

workflows:
    build_test:
      jobs:
        - build
        - node/test:
            requires:
              - build