version: '2.1'
orbs:
  codecov: codecov/codecov@3.1.1
  node: circleci/node@4.7.0
workflows:
  upload-to-codecov:
    jobs:
      - node/test:
          app-dir: "~/project/qna"
          run-command: "test:cov"
          post-steps:
            - codecov/upload