version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  deployECR:


workflows:
    build-test-deploy:
      jobs:
        - build
        - node/test:
            requires:
              - build
        - aws-ecr/build-and-push-image:
            repo: "${AWS_RESOURCE_NAME_PREFIX}"
            tag: "${CIRCLE_SHA1}"
            requires: 
              - node/test
        